version: 2.1

setup: true

orbs:
  to-kill-a-mocking-bird:
    orbs:
      continuation: circleci/continuation@0.5.0
    
    commands:
      folder1:
        steps:
          - checkout

          - run:
              name: Fetch branches
              command: git branch

          - run:  
              name: Check for changes in folder
              command: |
                if git diff --quiet master2.0 master2.0-dev -- ./src; then 
                  echo "No changes in specified folder."
                else 
                  echo "frontend" >> ./modules.txt
                  echo "Changes detected continuing with build";
                fi

          - run:
              name: Check for changes in folder
              command: |
                if git diff --quiet master2.0..master2.0-dev -- ./cypress; then 
                  echo "No changes in specified folder."
                else 
                  echo "server" >> ./modules.txt
                  echo "Changes detected continuing with build";
                fi

          - store_artifacts:
              path: ./modules.txt

      merge-configs:
        parameters:
          modules:
            type: string
            default: ./modules.txt
          frontend-config-loc:
            type: string
            default: ./server-config.yml
          server-config-loc:
            type: string
            default: ./server-config.yml
          continue-config:
            type: string
            default: .circleci/continue-config.yml
        steps:
          - checkout

          - run:
              name: Merge configs
              command: |
                # If `modules` is unavailable, stop this job without continuation
                if [ ! -f "<< parameters.modules >>" ] || [ ! -s "<< parameters.modules >>" ]
                then
                  echo 'Nothing to merge. Halting the job.'
                  circleci-agent step halt
                  exit
                fi

                # Convert a list of dirs to a list of config.yml
                sed -i -e 's/^/.circleci\//; s/$/-config.yml/g' "<< parameters.modules >>"

                xargs -a "<< parameters.modules >>" yq -y -s 'reduce .[] as $item ({}; . * $item)' | tee "<< parameters.continue-config >>"

          - store_artifacts:
              path: ./modules.txt
          - store_artifacts:
              path: .circleci/continue-config.yml

    jobs:
      the-greatest-showman:
        docker:
          - image: cimg/python:3.9
        steps:
          - checkout
          - run:
              name: Install yq
              command: pip install yq
          - folder1
          - merge-configs
          - continuation/continue:
              configuration_path: .circleci/continue-config.yml

workflows:
  the_great_gatsby:
    jobs:
      - to-kill-a-mocking-bird/the-greatest-showman