# TODO tests are not yet completed
version: 2.1

orbs:
  cypress: cypress-io/cypress@3


jobs:
  e2e-tests:
    docker:
      - image: node:latest
    steps:
      - checkout

      - run:
          name: install pnpm
          command: "npm i -g pnpm && cd ./app && pnpm install"

      - run:
          name: update apt
          command: apt-get update

      - run:
          name: install system deps
          command: apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - cypress/run-tests:
          start-command: pnpm dev
          cypress-command: "npx wait-on@latest http://localhost:3000 && npx cypress run"
          working-directory: app

      - store_artifacts:
          path: ./app/cypress/screenshots
          when: on_fail




workflows:
  the-great-gatsby:
    jobs:
      - e2e-tests:
          filters:
            branches:
              only:
                - main2.0
