version: 2.1
orbs:
  cypress: cypress-io/cypress@3.2.1

parameters:
  run_frontend_tests:
    type: boolean
    default: false
  run_changes_in_backend:
    type: boolean
    default: false

jobs:
  install_git:
    docker:
      - image: docker:20.10.11
    steps:
      - run:
          name: Adding git
          command: apk add git
      - persist_to_workspace:
          root: /
          paths:
            - usr/

  changes_in_frontend:
    docker:
      - image: docker:20.10.11
    steps:
      - attach_workspace:
          at: /
      - checkout

      - run:
          name: Check for changes in folder
          command: |
            if git diff --quiet HEAD^..HEAD ./app; then 
              echo "No changes in specified folder."
              circleci-agent step halt
            else 
              echo "Changes detected continuing with build";
            fi
      - run:
          command: echo " << pipeline.parameters.run_frontend_tests >>"

  run_frontend_test:
    docker:
      - image: node:latest
    steps:
      - checkout

      - run:
          name: install deps
          command: "npm i"

      - run:
          name: update apt
          command: apt-get update

      - run:
          name: install system deps
          command: apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - cypress/run-tests:
          cypress-command: "npx cypress run --component"

      - run:
          name: Run app
          command: "npm start"
          background: true

      - run:
          name: Wait for app
          command: sleep 10

      - cypress/run-tests:
          cypress-command: "npx cypress run"

  # push_frontend_to_production:
  #   docker:
  #     - image: node:latest
  #   steps:
  #     - attach_workspace:
  #         at: /
  #     - checkout

  #     - run:
  #         name: Push to main2.0 - Production branch
  #         command: git push origin master2.0-dev:master

workflows:
  the_great_gatsby:
    jobs:
      - install_git
      - changes_in_frontend:
          requires:
            - install_git

  the_great_depression:
    when: << pipeline.parameters.run_frontend_tests >>
    jobs:
      - run_frontend_test:
          filters:
            branches:
              only:
                - master2.0-dev
          requires:
            - changes_in_frontend
