version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  the_great_gatsby:
    jobs:
      - path-filtering/filter:
          name: check updated files
          mapping: |
            ./src/.* run_frontend_tests true
          base-revision: master
          config-path: .circleci/continue_config.yml