version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.1
  continuation: circleci/continuation@0.5.0

jobs:
  folder1:
    docker:
      - image: node:latest

    steps:
      - checkout

      - run:
          name: Check for changes in folder
          command: |
            if git diff --quiet HEAD^..HEAD ./src; then 
              echo "No changes in specified folder."
            else 
              echo "frontend" >> ./modules.txt
              echo "Changes detected continuing with build";
            fi

      - run:
          name: Check for changes in folder
          command: |
            if git diff --quiet HEAD^..HEAD ./cypress; then 
              echo "No changes in specified folder."
            else 
              echo "server" >> ./modules.txt
              echo "Changes detected continuing with build";
            fi

      - store_artifacts:
          path: ./modules.txt

  merge-configs:
    parameters:
      modules:
        type: string
        default: modules.txt
      frontend-config-loc:
        type: string
        default: ./server-config.yml
      server-config-loc:
        type: string
        default: ./server-config.yml
      continue-config:
        type: string
        default: ./continue-config.yml

    docker:
      - image: node:latest

    steps:
      - checkout

      - run:
          name: Merge configs
          command: |
            # If `modules` is unavailable, stop this job without continuation
            if [ ! -f "<< parameters.modules >>" ] || [ ! -s "<< parameters.modules >>" ]
            then
              echo 'Nothing to merge. Halting the job.'
              circleci-agent step halt
              exit
            fi

            # Convert a list of dirs to a list of config.yml
            sed -i -e 's/^/.circleci\//; s/$/-config.yml/g' "<< parameters.modules >>"

            xargs -a "<< parameters.modules >>" yq -y -s 'reduce .[] as $item ({}; . * $item)' | tee "<< parameters.continue-config >>"

workflows:
  the_great_gatsby:
    jobs:
      - folder1
      - merge-configs:
          requires:
            - folder1
      - continuation/continue:
          configuration_path: .circleci/continue_config.yml
          requires:
            - merge-configs
