version: 2.1
orbs:
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  the_great_gatsby:
    jobs:
      - path-filtering/filter:
          name: check updated files
          mapping: |
            app/.* run_frontend_tests true
            server/.* run_backend_deploy true
          base-revision: master
          config-path: .circleci/continue_config.yml