version: 2.1

orbs:
  cypress: cypress-io/cypress@3.2.1

parameters:
  run_frontend_tests:
    type: boolean
    default: false
  run_backend_deploy:
    type: boolean
    default: false

jobs:
  frontend_tests:
    docker:
      - image: cimg:latest
    steps:
      - checkout

      - run:
          name: Push
          command: git push origin master2.0-dev:master
      

workflows:
  the_great_depression:
    when: ${<< pipeline.parameters.run_frontend_tests >>}
    jobs:
      - frontend_tests:
          filters:
            branches:
              only:
                - master2.0-dev
