version: 2.1

orbs:
  cypress: cypress-io/cypress@3.2.1

jobs:
  frontend_tests:
    docker:
      - image: node:latest
        environment:
          VERCEL_ORG_ID: $VERCEL_ORG_ID
          VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
    steps:
      - checkout
      
      - run:
          name: Install Vercel CLI
          command: npm install --global vercel@latest
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment=preview --token=$TOKEN
      - run:
          name: Build Project Artifacts
          command: vercel build --token=$TOKEN
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --prebuilt --token=$TOKEN

  # production_deployment:
  #   docker:
  #     - image: circleci/node:latest
  #   environment:
  #     VERCEL_ORG_ID: $ORG_ID
  #     VERCEL_PROJECT_ID: $PROJECT_ID
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install Vercel CLI
  #         command: npm install --global vercel@latest
  #     - run:
  #         name: Pull Vercel Environment Information
  #         command: vercel pull --yes --environment=production --token=$TOKEN
  #     - run:
  #         name: Build Project Artifacts
  #         command: vercel build --prod --token=$TOKEN
  #     - run:
  #         name: Deploy Project Artifacts to Vercel
  #         command: vercel deploy --prebuilt --prod --token=$TOKEN

workflows:
  the_great_depression_1:
    jobs:
      - frontend_tests
      # - production_deployment